```{r}
library(tidyverse)
library(brms)
library(nanoparquet)
library(here)
library(tidybayes)
```

The reason we have to order the factor levels has to do with the current way sample_pbp is saving parquet files. It seems like the ordering is being stripped in the process.

```{r}
data_sample <- read_parquet(here("02_data", "02-3_data_modeling", "sample_5000_factor.parquet"))

data_sample <- data_sample |> 
  mutate(defender_foul_count = factor(defender_foul_count, 
                                   levels = 0:5,
                                   ordered = TRUE))

data_sample_10000 <- read_parquet(here("02_data", "02-3_data_modeling", "sample_10000_factor.parquet"))

data_sample_10000 <- data_sample_10000 |> 
  mutate(defender_foul_count = factor(defender_foul_count, 
                                   levels = 0:5,
                                   ordered = TRUE))

data_sample_30000 <- read_parquet(here("02_data", "02-3_data_modeling", "sample_30000_factor.parquet"))

data_sample_30000 <- data_sample_30000 |> 
  mutate(defender_foul_count = factor(defender_foul_count, 
                                   levels = 0:5,
                                   ordered = TRUE))

data_sample_60000 <- read_parquet(here("02_data", "02-3_data_modeling", "sample_60000_factor.parquet"))

data_sample_60000 <- data_sample_60000 |> 
  mutate(defender_foul_count = factor(defender_foul_count, 
                                   levels = 0:5,
                                   ordered = TRUE))

data_sample_100000 <- read_parquet(here("02_data", "02-3_data_modeling", "sample_1e+05_factor.parquet"))

data_sample_100000 <- data_sample_100000 |> 
  mutate(defender_foul_count = factor(defender_foul_count, 
                                   levels = 0:5,
                                   ordered = TRUE))

data_sample_full <- read_parquet(here("02_data", "02-3_data_modeling", "sample_359266_factor.parquet"))

data_sample_full <- data_sample_full |> 
  mutate(defender_foul_count = factor(defender_foul_count, 
                                   levels = 0:5,
                                   ordered = TRUE))

data_sample_full_agg <- data_sample_full |> 
  group_by(offensive_team, defensive_team, shot_movement, shot_type_basic, shot_zone, defender_position, defender_foul_count) |> 
  summarize(shots_defended_made = sum(shots_defended_made),
         shots_defended_total = sum(shots_defended_total))

data_sample_100000_agg <- data_sample_100000 |> 
  group_by(offensive_team, defensive_team, shot_movement, shot_type_basic, shot_zone, defender_position, defender_foul_count) |> 
  summarize(shots_defended_made = sum(shots_defended_made),
         shots_defended_total = sum(shots_defended_total))
```

```{r}
foul_neg_binomial_formula_varying_slopes_mo <- bf(
  shots_defended_total ~ 
    1 + mo(defender_foul_count) +
    (1 + mo(defender_foul_count) | shot_zone) +
    (1 + mo(defender_foul_count) | shot_movement) +
    (1 + mo(defender_foul_count) | shot_type_basic) +
    (1 + mo(defender_foul_count) | shot_technique) +
    (1 + mo(defender_foul_count) | shot_situation) +
    (1 + mo(defender_foul_count) | defender_position) +
    (1 + mo(defender_foul_count) | primary_defender) +
    (1 | offensive_team)
)

foul_neg_binomial_formula_varying_slopes_mo_2 <- bf(
  shots_defended_total ~ 
    1 + mo(defender_foul_count) +
    (1 + mo(defender_foul_count) | shot_zone) +
    (1 + mo(defender_foul_count) | shot_movement) +
    (1 + mo(defender_foul_count) | shot_type_basic) +
    (1 + mo(defender_foul_count) | defender_position) +
    (1 + mo(defender_foul_count) | defensive_team) +
    (1 + mo(defender_foul_count) | offensive_team)
)

prior_custom_vs_mo <- c(
  prior(normal(0, 1), class = "Intercept"),  # Fixed effects, weakly regularizing
  prior(normal(0.2, 0.5), class = "b", coef = "modefender_foul_count"), # Likely positive effect, likely small
  prior(exponential(1), class = "sd"),
  prior(dirichlet(c(1, 1, 1, 1.5, 1.5)), class = "simo", coef = "modefender_foul_count1"),
  prior(lkj(2), class = "cor")
)
```

```{r}
foul_neg_binomial_model_vs_mo_60000 <- brm(
  formula = foul_neg_binomial_formula_varying_slopes_mo,
  data = data_sample_60000,
  family = negbinomial(),
  prior = prior_custom_vs_mo,
  chains = 4,
  cores = 4,
  iter = 2000,
  warmup = 1000,
  seed = 42,
  control = list(adapt_delta = 0.95),
  backend = "cmdstanr",
  file = ("foul_neg-binomial_model_vs_mo_60000.rds")
)

foul_neg_binomial_model_vs_mo_2_100000 <- brm(
  formula = foul_neg_binomial_formula_varying_slopes_mo_2,
  data = data_sample_100000_agg,
  family = negbinomial(),
  prior = prior_custom_vs_mo,
  chains = 4,
  cores = 4,
  iter = 2000,
  warmup = 1000,
  seed = 42,
  control = list(adapt_delta = 0.95),
  backend = "cmdstanr",
  file = ("foul_neg-binomial_model_vs_mo_2_100000.rds")
)

foul_binomial_model_vs_mo_3_30000 <- brm(
  formula = foul_binomial_formula_varying_slopes_mo_3,
  data = data_sample_30000,
  family = binomial(link = "logit"),
  prior = prior_custom_vs_mo,
  chains = 4,
  cores = 4,
  iter = 2000,
  warmup = 1000,
  seed = 42,
  control = list(adapt_delta = 0.95),
  backend = "cmdstanr",
  file = ("foul_binomial_model_vs_mo_3_30000.1.rds")
)

foul_binomial_model_vs_mo_3_60000 <- brm(
  formula = foul_binomial_formula_varying_slopes_mo_3,
  data = data_sample_60000,
  family = binomial(link = "logit"),
  prior = prior_custom_vs_mo,
  chains = 4,
  cores = 4,
  iter = 2000,
  warmup = 1000,
  seed = 42,
  control = list(adapt_delta = 0.95),
  backend = "cmdstanr",
  file = ("foul_binomial_model_vs_mo_3_60000.rds")
)

foul_binomial_model_vs_mo_4_100000 <- brm(
  formula = foul_binomial_formula_varying_slopes_mo_4,
  data = data_sample_100000,
  family = binomial(link = "logit"),
  prior = prior_custom_vs_mo,
  chains = 4,
  cores = 4,
  iter = 2000,
  warmup = 1000,
  seed = 42,
  control = list(adapt_delta = 0.95),
  backend = "cmdstanr",
  file = ("foul_binomial_model_vs_mo_4_100000.rds")
)

foul_binomial_model_vs_mo_5_10000 <- brm(
  formula = foul_binomial_formula_varying_slopes_mo_5,
  data = data_sample_10000,
  family = binomial(link = "logit"),
  prior = prior_custom_vs_mo,
  chains = 4,
  cores = 4,
  iter = 2000,
  warmup = 1000,
  seed = 42,
  control = list(adapt_delta = 0.95),
  backend = "cmdstanr",
  file = ("foul_binomial_model_vs_mo_5_10000.rds")
)

foul_zero_binomial_model_vs_mo_5_10000 <- brm(
  formula = foul_binomial_formula_varying_slopes_mo_5,
  data = data_sample_10000,
  family = zero_inflated_binomial(link = "logit", link_zi = "logit"),
  prior = prior_custom_vs_mo,
  chains = 4,
  cores = 4,
  iter = 2000,
  warmup = 1000,
  seed = 42,
  control = list(adapt_delta = 0.95),
  backend = "cmdstanr",
  file = ("foul_zeero_binomial_model_vs_mo_5_10000.rds")
)

foul_binomial_model_vs_mo_5_30000 <- brm(
  formula = foul_binomial_formula_varying_slopes_mo_5,
  data = data_sample_30000,
  family = binomial(link = "logit"),
  prior = prior_custom_vs_mo,
  chains = 4,
  cores = 4,
  iter = 2000,
  warmup = 1000,
  seed = 42,
  control = list(adapt_delta = 0.95),
  backend = "cmdstanr",
  file = ("foul_binomial_model_vs_mo_5_30000.rds")
)

foul_binomial_model_vs_mo_5_100000 <- brm(
  formula = foul_binomial_formula_varying_slopes_mo_5,
  data = data_sample_100000,
  family = binomial(link = "logit"),
  prior = prior_custom_vs_mo,
  chains = 4,
  cores = 4,
  iter = 2000,
  warmup = 1000,
  seed = 42,
  control = list(adapt_delta = 0.95),
  backend = "cmdstanr",
  file = ("foul_binomial_model_vs_mo_5_100000.rds")
)

foul_binomial_model_vs_mo_2 <- brm(
  formula = foul_binomial_formula_varying_slopes_mo_2,
  data = data_sample,
  family = binomial(link = "logit"),
  prior = prior_custom_vs_mo,
  chains = 4,
  cores = 4,
  iter = 2000,
  warmup = 1000,
  seed = 42,
  control = list(adapt_delta = 0.95),
  backend = "cmdstanr",
  file = ("foul_binomial_model_vs_mo_2_10000.rds")
)
```

```{r}
foul_binomial_model_vs_1_10000 <- read_rds("foul_binomial_model_vs_1_10000.rds")

foul_binomial_model_vi_1_10000 <- read_rds("foul_binomial_model_vi_1_10000.rds")

foul_binomial_model_vs_mo_1_10000 <- read_rds("foul_binomial_model_vs_mo_1_10000.rds")

foul_binomial_model_vs_mo_2_10000 <- read_rds("foul_binomial_model_vs_mo_2_10000.rds")

loo_1 <- loo(foul_binomial_model_vs_mo_5_10000)

loo_2 <- loo(foul_zero_binomial_model_vs_mo_5_10000)

loo_3 <- loo_subsample(foul_binomial_model_vs_1_10000)

loo_4 <- loo(foul_binomial_model_vi_1_10000)

loo_5 <- loo(foul_binomial_model_vs_mo_1_10000)

loo_6 <- loo(foul_binomial_model_vs_mo_2_10000)

loo_compare(loo_1, loo_2)
```


```{r}
summary(foul_binomial_model_vs_mo_3_30000)
mcmc_plot(foul_binomial_model_vs_mo_3_30000)
plot(foul_binomial_model_vs_mo_5_30000)
marginal_effects(foul_binomial_model_vs_mo_3_30000)

# Load additional visualization packages
library(tidybayes)
library(ggdist)
library(patchwork)

# 1. Monotonic effect visualization
monotonic_effect <- foul_neg_binomial_model_vs_mo_60000 %>%
  spread_draws(b_Intercept, simo_modefender_foul_count1[category]) %>%
  mutate(
    # Calculate the cumulative effect for each foul count
    effect_0 = b_Intercept,
    effect_1 = b_Intercept + simo_modefender_foul_count1[1],
    effect_2 = b_Intercept + simo_modefender_foul_count1[1] + simo_modefender_foul_count1[2],
    effect_3 = b_Intercept + simo_modefender_foul_count1[1] + simo_modefender_foul_count1[2] + simo_modefender_foul_count1[3],
    effect_4 = b_Intercept + simo_modefender_foul_count1[1] + simo_modefender_foul_count1[2] + simo_modefender_foul_count1[3] + simo_modefender_foul_count1[4],
    effect_5 = b_Intercept + simo_modefender_foul_count1[1] + simo_modefender_foul_count1[2] + simo_modefender_foul_count1[3] + simo_modefender_foul_count1[4] + simo_modefender_foul_count1[5]
  ) %>%
  pivot_longer(cols = starts_with("effect_"), names_to = "foul_count", values_to = "effect") %>%
  mutate(foul_count = as.numeric(str_extract(foul_count, "\\d+"))) %>%
  ggplot(aes(x = foul_count, y = effect)) +
  stat_lineribbon(.width = c(0.5, 0.8, 0.95), alpha = 0.3) +
  scale_fill_brewer() +
  labs(
    title = "Monotonic Effect of Foul Count on Shot Success",
    subtitle = "Showing cumulative effect of increasing foul counts",
    x = "Defender Foul Count",
    y = "Log-Odds of Shot Success",
    fill = "Credible Interval"
  ) +
  theme_minimal()


# 1. Monotonic effect visualization
monotonic_effect_spread <- foul_binomial_model_vs_mo_4_100000 %>%
  spread_draws(simo_modefender_foul_count1[foul_count]) %>%
  mean_qi() |> 
  ggplot(aes(x = simo_modefender_foul_count1, y = foul_count, xmin = .lower, xmax = .upper)) +
  geom_pointinterval()
  
monotonic_effect_spread_2 <- foul_binomial_model_vs_mo_4_100000 %>%
  spread_draws(b_Intercept, simo_modefender_foul_count1[foul_count]) %>%
  mutate(effect = b_Intercept + simo_modefender_foul_count1) |> 
  median_qi() |> 
  ggplot(aes(x = effect, y = foul_count, xmin = effect.lower, xmax = effect.upper)) +
  geom_pointinterval()

monotonic_effect_spread_3 <- foul_binomial_model_vs_mo_5_100000 %>%
  spread_draws(b_Intercept, r_primary_defender[defender,], simo_modefender_foul_count1[foul_count]) %>%
  mutate(effect = b_Intercept + r_primary_defender + simo_modefender_foul_count1) |> 
  median_qi(effect) 

bottom_20 <- monotonic_effect_spread_3 |> 
  ungroup() |> 
  group_by(defender, foul_count) |> 
  arrange(desc(effect)) %>%
  head(20)

top_20 <- monotonic_effect_spread_3 |> 
  ungroup() |> 
  group_by(defender, foul_count) |> 
  arrange(effect) %>%
  head(20)

 monotonic_effect_spread_3 |>
  filter(defender %in% top_20$defender |defender  %in% bottom_20$defender) |> 
  ggplot(aes(x = effect, y = reorder(defender, effect), color = foul_count, xmin = .lower, xmax = .upper)) +
  geom_pointinterval()

```
 
```{r}

mutate(
    # Calculate the cumulative effect for each foul count
    effect_0 = b_Intercept,
    effect_1 = b_Intercept + simo_modefender_foul_count1[1],
    effect_2 = b_Intercept + simo_modefender_foul_count1[1] + simo_modefender_foul_count1[2],
    effect_3 = b_Intercept + simo_modefender_foul_count1[1] + simo_modefender_foul_count1[2] + simo_modefender_foul_count1[3],
    effect_4 = b_Intercept + simo_modefender_foul_count1[1] + simo_modefender_foul_count1[2] + simo_modefender_foul_count1[3] + simo_modefender_foul_count1[4],
    effect_5 = b_Intercept + simo_modefender_foul_count1[1] + simo_modefender_foul_count1[2] + simo_modefender_foul_count1[3] + simo_modefender_foul_count1[4] + simo_modefender_foul_count1[5]
  ) %>%
  pivot_longer(cols = starts_with("effect_"), names_to = "foul_count", values_to = "effect") %>%
  mutate(foul_count = as.numeric(str_extract(foul_count, "\\d+"))) %>%
  ggplot(aes(x = foul_count, y = effect)) +
  stat_lineribbon(.width = c(0.5, 0.8, 0.95), alpha = 0.3) +
  scale_fill_brewer() +
  labs(
    title = "Monotonic Effect of Foul Count on Shot Success",
    subtitle = "Showing cumulative effect of increasing foul counts",
    x = "Defender Foul Count",
    y = "Log-Odds of Shot Success",
    fill = "Credible Interval"
  ) +
  theme_minimal()

# 3. Team-level random effects with monotonic slopes
team_effects <- foul_binomial_model_vs_mo_4_100000 %>%
  spread_draws(r_offensive_team[team,]) %>%
  ggplot(aes(x = r_offensive_team, y = reorder(team, r_offensive_team))) +
  stat_halfeye() +
  labs(
    title = "Team-Level Random Intercepts",
    x = "Random Effect",
    y = "Team"
  ) +
  theme_minimal() +
  theme(axis.text.y = element_text(size = 6))

# 4. Position-level random effects with monotonic slopes
position_effects <- foul_binomial_model_vs_mo_1 %>%
  spread_draws(r_defender_position[position,], r_defender_position_modefender_foul_count[position,]) %>%
  ggplot(aes(x = r_defender_position, y = position)) +
  stat_halfeye() +
  labs(
    title = "Position-Level Random Intercepts",
    x = "Random Effect",
    y = "Position"
  ) +
  theme_minimal()

# 5. Player effects with monotonic slopes
player_effects <- foul_neg_binomial_model_vs_mo_60000 %>%
  spread_draws(r_primary_defender[primary_defender,]) %>%
  group_by(primary_defender) %>%
  summarise(
    mean_effect = mean(r_primary_defender),
    mean_slope = mean(r_primary_defender_modefender_foul_count),
    lower_95 = quantile(r_primary_defender, 0.025),
    upper_95 = quantile(r_primary_defender, 0.975)
  ) %>%
  arrange(mean_effect) %>%
  mutate(primary_defender = factor(primary_defender, levels = primary_defender)) %>%
  ggplot(aes(x = mean_effect, y = primary_defender)) +
  geom_point(aes(color = mean_slope), size = 2) +
  geom_errorbarh(aes(xmin = lower_95, xmax = upper_95), height = 0) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "red") +
  scale_color_gradient2(
    low = "blue",
    mid = "gray",
    high = "red",
    midpoint = 0,
    name = "Monotonic Slope"
  ) +
  labs(
    title = "Player-Level Defensive Effectiveness",
    subtitle = "Color indicates sensitivity to foul count",
    x = "Defensive Effect (log-odds)",
    y = "Player"
  ) +
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 6),
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 10)
  )

# 6. Monotonic simplex parameters visualization
simplex_plot <- foul_binomial_model_vs_mo_1 %>%
  spread_draws(simo_modefender_foul_count1[category]) %>%
  ggplot(aes(x = category, y = simo_modefender_foul_count1)) +
  stat_halfeye() +
  labs(
    title = "Monotonic Simplex Parameters",
    subtitle = "Showing the relative weights for each foul count level",
    x = "Foul Count Level",
    y = "Simplex Weight"
  ) +
  theme_minimal()

# 7. Correlation between intercept and monotonic slope by grouping
correlation_plot <- bind_rows(
  foul_binomial_model_vs_mo_1 %>%
    spread_draws(r_defender_position[position,], r_defender_position_modefender_foul_count[position,]) %>%
    mutate(group = "Position"),
  foul_binomial_model_vs_mo_1 %>%
    spread_draws(r_defense_distance_category[category,], r_defense_distance_category_modefender_foul_count[category,]) %>%
    mutate(group = "Distance"),
  foul_binomial_model_vs_mo_1 %>%
    spread_draws(r_defensive_team[team,], r_defensive_team_modefender_foul_count[team,]) %>%
    mutate(group = "Team"),
  foul_binomial_model_vs_mo_1 %>%
    spread_draws(r_primary_defender[player,], r_primary_defender_modefender_foul_count[player,]) %>%
    mutate(group = "Player")
) %>%
  ggplot(aes(x = r_defender_position, y = r_defender_position_modefender_foul_count)) +
  stat_density_2d(aes(fill = after_stat(level)), geom = "polygon") +
  facet_wrap(~group, scales = "free") +
  scale_fill_viridis_c() +
  labs(
    title = "Correlation between Intercept and Monotonic Slope",
    subtitle = "By grouping variable",
    x = "Random Intercept",
    y = "Random Monotonic Slope",
    fill = "Density"
  ) +
  theme_minimal()

# 8. Player-level monotonic effects
player_monotonic_effects <- foul_binomial_model_vs_mo_3_30000 %>%
  spread_draws(r_primary_defender[player,], r_primary_defender_modefender_foul_count[player,]) %>%
  group_by(player) %>%
  summarise(
    mean_intercept = mean(r_primary_defender),
    mean_slope = mean(r_primary_defender_modefender_foul_count),
    lower_95_slope = quantile(r_primary_defender_modefender_foul_count, 0.025),
    upper_95_slope = quantile(r_primary_defender_modefender_foul_count, 0.975)
  ) %>%
  arrange(mean_slope) %>%
  slice(c(1:10, (n()-9):n())) %>%  # Take top and bottom 10
  mutate(player = factor(player, levels = player)) %>%
  ggplot(aes(x = mean_slope, y = player)) +
  geom_point(size = 3) +
  geom_errorbarh(aes(xmin = lower_95_slope, xmax = upper_95_slope), height = 0) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "red") +
  labs(
    title = "Top and Bottom 10 Players by Monotonic Slope",
    subtitle = "Players most and least affected by accumulating fouls",
    x = "Monotonic Slope Effect",
    y = "Player"
  ) +
  theme_minimal() +
  theme(axis.text.y = element_text(size = 8))

# 9. Distance category monotonic effects
distance_monotonic_effects <- foul_binomial_model_vs_mo_1 %>%
  spread_draws(r_defense_distance_category[category,], r_defense_distance_category_modefender_foul_count[category,]) %>%
  group_by(category) %>%
  summarise(
    mean_intercept = mean(r_defense_distance_category),
    mean_slope = mean(r_defense_distance_category_modefender_foul_count),
    lower_95_slope = quantile(r_defense_distance_category_modefender_foul_count, 0.025),
    upper_95_slope = quantile(r_defense_distance_category_modefender_foul_count, 0.975)
  ) %>%
  ggplot(aes(x = mean_slope, y = category)) +
  geom_point(size = 3) +
  geom_errorbarh(aes(xmin = lower_95_slope, xmax = upper_95_slope), height = 0) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "red") +
  labs(
    title = "Monotonic Effects by Defense Distance",
    subtitle = "How different defensive distances are affected by foul accumulation",
    x = "Monotonic Slope Effect",
    y = "Defense Distance Category"
  ) +
  theme_minimal()

# Combine all plots
(monotonic_effect | simplex_plot) / 
  (correlation_plot) / 
  (player_monotonic_effects | distance_monotonic_effects) +
  plot_annotation(
    title = "Monotonic Model Analysis",
    subtitle = "Exploring the effects of foul accumulation across different levels",
    theme = theme(plot.title = element_text(hjust = 0.5))
  )

defender_positions <- data_sample_30000 |> 
  select(primary_defender, defender_position) |>
  mutate(primary_defender = str_replace_all(primary_defender, " ", "\\.")) |> 
  distinct()

# Get player effects with positions
player_effects_with_positions <- foul_binomial_model_vs_mo_3_30000 %>%
  spread_draws(r_primary_defender[primary_defender,]) %>%
  group_by(primary_defender) %>%
  summarise(
    mean_effect = mean(r_primary_defender),
    lower_95 = quantile(r_primary_defender, 0.025),
    upper_95 = quantile(r_primary_defender, 0.975)
  ) %>%
  left_join(defender_positions, by = "primary_defender")

# Get top and bottom 10 players by position
top_bottom_by_position <- player_effects_with_positions %>%
  group_by(defender_position) %>%
  arrange(desc(mean_effect)) %>%
  slice(c(1:10, (n()-9):n())) %>%
  ungroup()

# Get distance effects for these players
player_distance_effects <- foul_binomial_model_vs_mo_3_30000 %>%
  spread_draws(r_primary_defender[primary_defender,], r_shot_zone[category,]) %>%
  # Calculate the combined effect for each player and distance category
  mutate(combined_effect = r_primary_defender + r_shot_zone) %>%
  # Filter to only include our selected players
  filter(primary_defender %in% top_bottom_by_position$primary_defender) %>%
  # Get summary statistics
  group_by(primary_defender, category) |> 
  summarise(
    mean_effect = mean(combined_effect),
    lower_95 = quantile(combined_effect, 0.025),
    upper_95 = quantile(combined_effect, 0.975)
  ) %>%
  # Add position information
  left_join(defender_positions, by = "primary_defender") %>%
  # Add overall effect for ordering
  left_join(
    top_bottom_by_position %>% select(primary_defender, mean_effect),
    by = "primary_defender",
    suffix = c("_distance", "_overall")
  )

player_distance_effects |> 
  ggplot(aes(x = mean_effect_distance, y = reorder(primary_defender, mean_effect_overall))) +
  geom_point(aes(color = category), size = 3) +
  geom_errorbarh(aes(xmin = lower_95, xmax = upper_95, color = category), height = 0) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "red") +
  facet_wrap(~defender_position, scales = "free_y", ncol = 1) +
  labs(
    title = "Top and Bottom 10 Defensive Players by Position",
    subtitle = "Showing effectiveness at different defensive distances",
    x = "Defensive Effect (log-odds)",
    y = "Player",
    color = "Defense Distance"
  ) +
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 8),
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 10),
    legend.position = "bottom",
    strip.text = element_text(size = 12, face = "bold")
  ) +
  scale_color_brewer(palette = "Set1")

# Check available parameters
print(names(foul_binomial_model_vs_mo_1$fit))
```

```{r}
summary(foul_binomial_model_vs_mo_2)
mcmc_plot(foul_binomial_model_vs_mo_2)
plot(foul_binomial_model_vs_mo_2)
marginal_effects(foul_binomial_model_vs_mo_2)

# Load additional visualization packages
library(tidybayes)
library(ggdist)
library(patchwork)

# 1. Monotonic effect visualization
monotonic_effect <- foul_binomial_model_vs_mo_2 %>%
  spread_draws(b_Intercept, simo_modefender_foul_count1[category]) %>%
  mutate(
    # Calculate the cumulative effect for each foul count
    effect_0 = b_Intercept,
    effect_1 = b_Intercept + simo_modefender_foul_count1[1],
    effect_2 = b_Intercept + simo_modefender_foul_count1[1] + simo_modefender_foul_count1[2],
    effect_3 = b_Intercept + simo_modefender_foul_count1[1] + simo_modefender_foul_count1[2] + simo_modefender_foul_count1[3],
    effect_4 = b_Intercept + simo_modefender_foul_count1[1] + simo_modefender_foul_count1[2] + simo_modefender_foul_count1[3] + simo_modefender_foul_count1[4],
    effect_5 = b_Intercept + simo_modefender_foul_count1[1] + simo_modefender_foul_count1[2] + simo_modefender_foul_count1[3] + simo_modefender_foul_count1[4] + simo_modefender_foul_count1[5]
  ) %>%
  pivot_longer(cols = starts_with("effect_"), names_to = "foul_count", values_to = "effect") %>%
  mutate(foul_count = as.numeric(str_extract(foul_count, "\\d+"))) %>%
  ggplot(aes(x = foul_count, y = effect)) +
  stat_lineribbon(.width = c(0.5, 0.8, 0.95), alpha = 0.3) +
  scale_fill_brewer() +
  labs(
    title = "Monotonic Effect of Foul Count on Shot Success",
    subtitle = "Showing cumulative effect of increasing foul counts",
    x = "Defender Foul Count",
    y = "Log-Odds of Shot Success",
    fill = "Credible Interval"
  ) +
  theme_minimal()

# Get player effects with positions
player_effects_with_positions <- foul_neg_binomial_model_vs_mo_60000 %>%
  spread_draws(r_primary_defender[primary_defender,]) %>%
  group_by(primary_defender) %>%
  summarise(
    mean_effect = mean(r_primary_defender),
    lower_95 = quantile(r_primary_defender, 0.025),
    upper_95 = quantile(r_primary_defender, 0.975)
  ) %>%
  left_join(defender_positions, by = "primary_defender")

# Get top and bottom 10 players by position
top_bottom_by_position <- player_effects_with_positions %>%
  group_by(defender_position) %>%
  arrange(desc(mean_effect)) %>%
  slice(c(1:10, (n()-9):n())) %>%
  ungroup()

# Get distance effects for these players
player_distance_effects <- foul_binomial_model_vs_mo_2 %>%
  spread_draws(r_primary_defender[primary_defender,], r_defense_distance_category[category,]) %>%
  # Calculate the combined effect for each player and distance category
  mutate(combined_effect = r_primary_defender + r_defense_distance_category) %>%
  # Filter to only include our selected players
  filter(primary_defender %in% top_bottom_by_position$primary_defender) %>%
  # Get summary statistics
  group_by(primary_defender, category) |> 
  summarise(
    mean_effect = mean(combined_effect),
    lower_95 = quantile(combined_effect, 0.025),
    upper_95 = quantile(combined_effect, 0.975)
  ) %>%
  # Add position information
  left_join(defender_positions, by = "primary_defender") %>%
  # Add overall effect for ordering
  left_join(
    top_bottom_by_position %>% select(primary_defender, mean_effect),
    by = "primary_defender",
    suffix = c("_distance", "_overall")
  )

player_distance_effects |> 
  ggplot(aes(x = mean_effect_distance, y = reorder(primary_defender, mean_effect_overall))) +
  geom_point(aes(color = category), size = 3) +
  geom_errorbarh(aes(xmin = lower_95, xmax = upper_95, color = category), height = 0) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "red") +
  facet_wrap(~defender_position, scales = "free_y", ncol = 1) +
  labs(
    title = "Top and Bottom 10 Defensive Players by Position",
    subtitle = "Showing effectiveness at different defensive distances",
    x = "Defensive Effect (log-odds)",
    y = "Player",
    color = "Defense Distance"
  ) +
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 8),
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 10),
    legend.position = "bottom",
    strip.text = element_text(size = 12, face = "bold")
  ) +
  scale_color_brewer(palette = "Set1")
```

```{r}
defender_teams <- data_sample |> 
  select(primary_defender, defensive_team) |>
  mutate(primary_defender = str_replace_all(primary_defender, " ", "\\.")) |> 
  distinct()

# Create team-based player visualization
distance_player_effects <- foul_binomial_model_vs_mo_2 %>%
  spread_draws(r_primary_defender[primary_defender,], r_defense_distance_category[defense_distance_category,]) %>%
  group_by(primary_defender,defense_distance_category) %>%
  mutate(combined_effect = r_primary_defender + r_defense_distance_category) |> 
  summarise(
    mean_effect = mean(combined_effect),
    lower_95 = quantile(combined_effect, 0.025),
    upper_95 = quantile(combined_effect, 0.975)
  ) %>%
  left_join(defender_teams, by = "primary_defender") %>%
  # Calculate team averages
  group_by(defensive_team) %>%
  mutate(team_mean = mean(mean_effect)) %>%
  ungroup() %>%
  # Select top and bottom 5 teams
  filter(defensive_team %in% c(
    defensive_team[order(team_mean)][1:5],  # Bottom 5 teams
    defensive_team[order(team_mean)][(length(unique(defensive_team))-4):length(unique(defensive_team))]  # Top 5 teams
  )) %>%
  # Order teams and players
  arrange(team_mean, mean_effect) %>%
  mutate(
    defensive_team = factor(defensive_team, levels = unique(defensive_team)),
    primary_defender = factor(primary_defender, levels = unique(primary_defender))
  ) %>%
  ggplot(aes(x = mean_effect, y = primary_defender, color = defense_distance_category)) +
  geom_point(size = 2) +
  geom_errorbarh(aes(xmin = lower_95, xmax = upper_95), height = 0) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "red") +
  facet_wrap(~defensive_team, scales = "free_y", ncol = 2) +
  labs(
    title = "Player Defensive Effectiveness by Team",
    subtitle = "Showing top and bottom 5 teams by average defensive effectiveness",
    x = "Defensive Effect (log-odds)",
    y = "Player",
    color = "Defense Distance",
    caption = "Red line indicates average defensive effectiveness"
  ) +
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 8),
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 10),
    strip.text = element_text(size = 10, face = "bold"),
    legend.position = "bottom"
  ) +
  scale_color_brewer(palette = "Set1")

# Display the team-based player visualization
distance_player_effects_by_team
```

```{r}
library(duckplyr)

defender_teams <- data_sample_60000 |> 
  select(primary_defender, defensive_team) |>
  mutate(primary_defender = str_replace_all(primary_defender, " ", "\\.")) |> 
  distinct()

# Create team-based player visualization
team_player_effects_by_team_intercept <- foul_neg_binomial_model_vs_mo_60000 %>%
  spread_draws(r_primary_defender[primary_defender,], b_Intercept) %>%
  group_by(primary_defender) %>%
  mutate(combined_effect = r_primary_defender + b_Intercept) |> 
  summarise(
    mean_effect = mean(combined_effect),
    lower_95 = quantile(combined_effect, 0.025),
    upper_95 = quantile(combined_effect, 0.975)
  ) %>%
  left_join(defender_teams, by = "primary_defender") %>%
  # Calculate team averages
  group_by(defensive_team) %>%
  mutate(team_mean = mean(mean_effect)) %>%
  ungroup() %>%
  # Select top and bottom 5 teams
  filter(defensive_team %in% c(
    defensive_team[order(team_mean)][1:5],  # Bottom 5 teams
    defensive_team[order(team_mean)][(length(unique(defensive_team))-4):length(unique(defensive_team))]  # Top 5 teams
  )) %>%
  # Order teams and players
  arrange(team_mean, mean_effect) %>%
  mutate(
    defensive_team = factor(defensive_team, levels = unique(defensive_team)),
    primary_defender = factor(primary_defender, levels = unique(primary_defender))
  ) %>%
  ggplot(aes(x = mean_effect, y = primary_defender)) +
  geom_point(size = 2) +
  geom_errorbarh(aes(xmin = lower_95, xmax = upper_95), height = 0) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "red") +
  facet_wrap(~defensive_team, scales = "free_y", ncol = 2) +
  labs(
    title = "Player Defensive Effectiveness by Team",
    subtitle = "Showing top and bottom 5 teams by average defensive effectiveness",
    x = "Defensive Effect (log-odds)",
    y = "Player",
    color = "Defense Distance",
    caption = "Red line indicates average defensive effectiveness"
  ) +
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 8),
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 10),
    strip.text = element_text(size = 10, face = "bold"),
    legend.position = "bottom"
  ) +
  scale_color_brewer(palette = "Set1")

team_player_effects_by_team <- foul_neg_binomial_model_vs_mo_60000 %>%
  spread_draws(r_primary_defender[primary_defender,]) %>%
  group_by(primary_defender) %>%
  mutate(combined_effect = r_primary_defender) |> 
  summarise(
    mean_effect = mean(combined_effect),
    lower_95 = quantile(combined_effect, 0.025),
    upper_95 = quantile(combined_effect, 0.975)
  ) %>%
  left_join(defender_teams, by = "primary_defender") %>%
  # Calculate team averages
  group_by(defensive_team) %>%
  mutate(team_mean = mean(mean_effect)) %>%
  ungroup() %>%
  # Select top and bottom 5 teams
  filter(defensive_team == "GSW") %>%
  # Order teams and players
  arrange(team_mean, mean_effect) %>%
  mutate(
    defensive_team = factor(defensive_team, levels = unique(defensive_team)),
    primary_defender = factor(primary_defender, levels = unique(primary_defender))
  ) %>%
  ggplot(aes(x = mean_effect, y = primary_defender)) +
  geom_point(size = 2) +
  geom_errorbarh(aes(xmin = lower_95, xmax = upper_95), height = 0) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "red") +
  facet_wrap(~defensive_team, scales = "free_y") +
  labs(
    title = "Player Defensive Effectiveness by Team",
    subtitle = "Showing top and bottom 5 teams by average defensive effectiveness",
    x = "Defensive Effect (log-odds)",
    y = "Player",
    color = "Defense Distance",
    caption = "Red line indicates average defensive effectiveness"
  ) +
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 8),
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 10),
    strip.text = element_text(size = 10, face = "bold"),
    legend.position = "bottom"
  ) +
  scale_color_brewer(palette = "Set1")

# Display the team-based player visualization
team_player_effects_by_team

```

I don't like the below plot

```{r}
foul_neg_binomial_model_vs_mo_60000 |> 
  gather_draws(r_shot_movement[shot_movement,term]) |> 
  ggplot(aes(y = shot_movement, x = .value)) + 
  stat_halfeye() +
  facet_wrap(vars(term))

foul_neg_binomial_model_vs_mo_60000 |> 
  gather_draws(r_shot_type_basic[shot_type_basic,term]) |> 
  ggplot(aes(y = shot_type_basic, x = .value)) + 
  stat_halfeye()

foul_neg_binomial_model_vs_mo_60000 |> 
  gather_draws(r_shot_technique[shot_technique,term]) |> 
  ggplot(aes(y = shot_technique, x = .value)) + 
  stat_halfeye() +
  facet_wrap(vars(term))

foul_neg_binomial_model_vs_mo_60000 |> 
  gather_draws(r_shot_situation[shot_situation,term]) |> 
  ggplot(aes(y = shot_situation, x = .value)) + 
  stat_halfeye()

```


